language: node_js

cache:
  directories:
    - ~/.npm

notifications:
  email: false

node_js:
  - 'node'
  - 'lts/*'
  - '8'
  - '7'
  - '6'

script:
  - npm test

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
